repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: stable
    hooks:
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
    -   id: flake8
        args: [--max-line-length=80]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.6
