# Run-time parameters
#--------------------
run:
    envName   : SpaceInvaders-v4
    train     : True
    test      : False
    timeLimit : 30


# Training hyperparameters
#-------------------------
training:
    nEpisodes       : 1
    maxEpisodeSteps : 50000
    batchSize       : 64
    savePeriod      : 1
    QTrainer:
        enabled: True


# Network parameters
#-------------
brain:
    architecture : DQN
    discount     : 0.9
    learningRate : 0.00025
    loss         : mse
    optimizer    : adam
    VanillaQBrain:
        enabled: True


# Memory parameters
#------------------
memory:
    maxSize     : 100
    pretrainLen : 64
    ExperienceMemory:
        enabled: True


# Action selection parameters
#----------------------------
action:
    EpsilonGreedy:
        enabled      : True
        epsDecayRate : 0.00001
        epsilonStart : 1.0
        epsilonStop  : 0.01


# Navigation parameters
#----------------------
navigation:
    FrameByFrameNavigator:
        enabled: True


# Frame preprocessing parameters
#-------------------------------
frame:
    VanillaFrameManager:
        enabled    : True
        cropBot    : 12
        cropLeft   : 4
        cropRight  : 12
        cropTop    : 8
        shrinkCols : 84
        shrinkRows : 110
        traceLen   : 4
