# Run-time parameters
#--------------------
run:
    envName   : SpaceInvaders-v4
    train     : True
    test      : False
    render    : True
    plot      : False
    timeLimit : 30


# I/O parameters
#---------------
io:
    outputDir  : ~/Data/ai_data/test_run/output
    fileBase   : si


# Training hyperparameters
#-------------------------
training:
    mode:
        qtrainer:
            enable: True
    nEpisodes  : 1
    maxEpisodeSteps : 50000
    batchSize       : 64
    savePeriod : 1


# Network parameters
#-------------
network:
    architecture    : conv1
    discount        : 0.9
    learningRate    : 0.00025
    loss            : mse
    optimizer       : adam
    mode:
        vanillaQ:
            enable : True
        doubleDqn:
            enable : False
        fixedQ:
            enable      : False
            fixedQSteps : 100


# Memory parameters
#------------------
memory:
    maxSize   : 100
    pretrainLen  : 64
    priority:
        enable     : False
        perA       : 0.6
        perB       : 0.4
        perBAnneal : 0.001
        perE       : 0.01
    mode:
        experience:
            enable : True
        episode:
            enable : False


# Exploration parameters
#------------------------
explore:
    mode:
        epsilonGreedy:
            enable       : True
            epsDecayRate : 0.00001
            epsilonStart : 1.0
            epsilonStop  : 0.01


# Navigation parameters
#----------------------
navigation:
    mode:
        frameByFrame:
            enable: True


# Frame preprocessing parameters
#-------------------------------
frame:
    mode:
        vanilla:
            enable     : True
            cropBot    : 12
            cropLeft   : 4
            cropRight  : 12
            cropTop    : 8
            shrinkCols : 84
            shrinkRows : 110
            traceLen   : 4
