# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 80
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry]
name = 'anna'
version = "1.1.0"
description = ''
authors = ['Jared Coughlin']

[tool.poetry.dependencies]
python = '^3.6'
numpy = "^1.17"
pyyaml = "^5.1"
h5py = "^2.10"
gym = "^0.15.4"
atari_py = "^0.2.6"
cython = "^0.29.14"
scikit-image = "^0.16.2"
tk = "^0.1.0"
scipy = "^1.3"
imread = "^0.7.1"
tensorflow = "^2.1"
sphinx = "^2.3.1"


[tool.poetry.dev-dependencies]
ipython = "^7.9"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
